# Generated by Django 5.1.2 on 2024-10-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('guess_reason', models.CharField(max_length=256)),
                ('facebook', models.CharField(max_length=256)),
                ('instagram', models.CharField(max_length=256)),
                ('twitter', models.CharField(max_length=256)),
                ('strava', models.CharField(max_length=256)),
            ],
        ),
    ]
