# Generated by Django 5.1.2 on 2024-10-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batapi', '0004_guests_delete_guest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guest',
        ),
    ]
