# Generated by Django 5.1.2 on 2024-10-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batapi', '0005_rename_guests_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('why', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
