# Generated by Django 5.1.2 on 2024-10-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batapi', '0007_patent'),
    ]

    operations = [
        migrations.AddField(
            model_name='batguest',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
    ]
