# Generated by Django 5.1.2 on 2024-11-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batapi', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
